### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by erjdriver** [thisisjofrank/p2p-demo-ably#3]
I'm getting an error when I got into the api folder at the end and do `npm run start`

```
npm run start

> prestart
> func extensions install

No action performed. Extension bundle is configured in C:\Users\mini\git\p2p-demo-ably\api\host.json.

> func start

Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell, --custom]
Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell, --custom]
Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell, --custom]

Azure Functions Core Tools
Core Tools Version:       4.0.4915 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.14.0.19631

Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell, --custom]
Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell, --custom]
[2023-01-25T17:41:42.164Z] File 'C:\Program Files\dotnet\dotnet.exe' is not found, 'dotnet' invocation will rely on the PATH environment variable.
[2023-01-25T17:41:42.250Z] Referenced bundle Microsoft.Azure.Functions.ExtensionBundle of version 1.8.1 does not meet the required minimum version of 2.6.1. Update your extension bundle reference in host.json to reference 2.6.1 or later.
[2023-01-25T17:41:42.253Z] A host error has occurred during startup operation 'e0c1c963-b1d0-475f-a51b-b909c26f7c3f'.
f version 1.8.1 does not meet the required minimum version of 2.6.1. Update your extension bundle reference in host.json to reference 2.6.1 or later. For more information see https://aka.ms/func-min-bundle-versions.
Value cannot be null. (Parameter 'provider')
```

Also what does `npx live-server...` do and same for `npm run start`

**Comment by thisisjofrank** [comment]
I think you may need to do an 
npm install 
before you run the npm run start

**Comment by thisisjofrank** [comment]
Ah, it looks like there is a need for an update of the version of core tools.

**Comment by erjdriver** [comment]
I cloned the repository and did the following commands in sequence

```
$ npm install -g live-server
$ npm install -g azure-functions-core-tools
$ cd api
$ func settings add ABLY_API_KEY Your-Ably-Api-Key
$ npx live-server --proxy=/api:http://127.0.0.1:7071/api
$ cd api
$ npm run start
```

I got the error on the last one.

After I did the `npx`, I did get a new tab with the demo screen.

**Comment by erjdriver** [comment]
I edited the hosts.json file to

`    "version": "[2.*, 3.0.0)"`

and getting a little bit further

```
> prestart
> func extensions install

No action performed. Extension bundle is configured in C:\Users\mini\git\p2p-demo-ably\api\host.json.

> start
> func start

Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell, --custom]
Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell, --custom]
Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell, --custom]

Azure Functions Core Tools
Core Tools Version:       4.0.4915 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.14.0.19631

Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell, --custom]
Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell, --custom]
Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell, --custom]
[2023-01-25T19:38:33.161Z] File 'C:\Program Files\dotnet\dotnet.exe' is not found, 'dotnet' invocation will rely on the PATH environment variable.
[2023-01-25T19:38:33.571Z] File 'C:\Program Files\dotnet\dotnet.exe' is not found, 'dotnet' invocation will rely on the PATH environment variable.

Functions:

        createTokenRequest: [GET] http://localhost:7071/api/createTokenRequest

For detailed output, run func with --verbose flag.
[2023-01-25T19:38:34.264Z] Worker process started and initialized.
[2023-01-25T19:38:34.274Z] Worker was unable to load function createTokenRequest: 'Cannot find module 'ably/promises'
Require stack:
- C:\Users\mini\git\p2p-demo-ably\api\createTokenRequest\index.js
- C:\Users\mini\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\dist\src\worker-bundle.js
- C:\Users\mini\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\dist\src\nodejsWorker.js'
[2023-01-25T19:38:34.277Z] Worker failed to load function: 'createTokenRequest' with function id: '4ad472c0-dab5-4a52-9491-f53e350db07f'.
[2023-01-25T19:38:34.278Z] Result: Failure
Exception: Worker was unable to load function createTokenRequest: 'Cannot find module 'ably/promises'
Require stack:
- C:\Users\mini\git\p2p-demo-ably\api\createTokenRequest\index.js
- C:\Users\mini\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\dist\src\worker-bundle.js
- C:\Users\mini\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\dist\src\nodejsWorker.js'
Stack: Error: Worker was unable to load function createTokenRequest: 'Cannot find module 'ably/promises'
Require stack:
- C:\Users\mini\git\p2p-demo-ably\api\createTokenRequest\index.js
- C:\Users\mini\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\dist\src\worker-bundle.js
- C:\Users\mini\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\dist\src\nodejsWorker.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at Object.apply (C:\Users\mini\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\workers\node\dist\src\worker-bundle.js:2:41468)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\mini\git\p2p-demo-ably\api\createTokenRequest\index.js:1:14)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12).
[2023-01-25T19:38:38.819Z] Host lock lease acquired by instance ID '000000000000000000000000B8F5A266'.
```

In sum - the two relevant errors seem to be:

`File 'C:\Program Files\dotnet\dotnet.exe' is not found, 'dotnet' invocation will rely on the PATH environment variable.`

`Worker was unable to load function createTokenRequest: 'Cannot find module 'ably/promises'`

**Comment by erjdriver** [comment]
In the api folder, I did `npm install ably --save`

and now the second error re createTokenRequest is gone.

**Comment by thisisjofrank** [comment]
I'm afraid this is something that I'm not going to fix as this is an old repo and I am no longer employed by Ably, I'd recommend checking out their Ably Labs org where there are many other P2P demos.

**Comment by erjdriver** [comment]
Thank you.
